def add_post():
    title=input("Enter Post Title: ")
    post=input("Enter Post: ")
    counter=open("count.cms","r")
    count=int(counter.read())
    file=open(str(count)+".html","w+")
    file3=open("data.csv","a+")
    file3.write(title+","+post+"\n")
    file3.close()
    counter.close()
    counter=open("count.cms","w+")
    counter.write(str(count+1))
    counter.close()
    file.write("<HTML>\n")
    file.write("<Title>"+title+"</Title>")
    file.write("<Body>")
    file.write("<H1>"+title+"</H1>")
    file.write("<p>"+post+"</p>")
    file.close()
    file2=open("index.html","a+")
    file2.write("<a href=\""+str(count)+".html\">"+str(count)+"</a>")
    file2.close()
    print("Post Added Successfully")

if __name__=="__main__":
    add_post()